apiVersion: v1
kind: Service
metadata:
  name: ${NAMESPACE}-backend
  namespace: ${NAMESPACE}
spec:
  selector:
    app: ${NAMESPACE}-backend
  ports:
    - port: ${BACKEND_PORT}
      targetPort: ${BACKEND_PORT}
  type: ClusterIP