apiVersion: v1
kind: Service
metadata:
  name: alumnos-frontend
  namespace: alumnos
  annotations:
    # Classic Load Balancer público (in-tree cloud provider de EKS)
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: alumnos-frontend
  ports:
    - port: 80
      targetPort: 80
